name: agrovilla
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  carousel_slider: ^5.1.1
  mime: ^2.0.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner.jpg
    - assets/images/banner2.jpg
    - assets/images/peach.jpg
    - assets/images/avocado.jpg
    - assets/images/login_banner.jpg
